name: private_chat
description: "A secure private chat app with encrypted messaging and local storage."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  sqflite: ^2.3.3
  flutter_secure_storage: ^9.0.0
  workmanager:
    path: ../flutter_workmanager-main/workmanager
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true